package compiler

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/blackzig/zigguard/internal/policy"
)

const ManagedMarker = "<!-- Generated by ZigGuard. DO NOT EDIT. -->"

type Artifact struct {
	Target     string
	Path       string
	Capability string
	Content    string
}

type manifest struct {
	PolicyVersion string          `json:"policy_version"`
	Project       string          `json:"project"`
	Bindings      []targetBinding `json:"bindings"`
}

type targetBinding struct {
	Target     string `json:"target"`
	Surface    string `json:"surface"`
	Capability string `json:"capability"`
}

func Compile(p policy.Policy) ([]Artifact, error) {
	if err := p.Validate(); err != nil {
		return nil, err
	}

	targets := p.SortedTargets()
	selected := make(map[string]bool, len(targets))
	for _, target := range targets {
		selected[target] = true
	}

	var artifacts []Artifact
	var bindings []targetBinding

	sharedConsumers := make([]string, 0, 3)
	for _, target := range []string{"codex", "copilot", "cursor"} {
		if selected[target] {
			sharedConsumers = append(sharedConsumers, target)
			bindings = append(bindings, targetBinding{
				Target:     target,
				Surface:    "AGENTS.md",
				Capability: "instruction-context",
			})
		}
	}

	if len(sharedConsumers) > 0 {
		artifacts = append(artifacts, Artifact{
			Target:     "shared",
			Path:       "AGENTS.md",
			Capability: "instruction-context",
			Content:    renderAgentPolicy(p, "Shared ZigGuard policy for "+strings.Join(sharedConsumers, ", ")),
		})
	}

	if selected["claude"] {
		content := ""
		if len(sharedConsumers) > 0 {
			content = ManagedMarker + "\n\n@AGENTS.md\n\n" +
				"# Claude Code\n\n" +
				"The imported AGENTS.md file is the ZigGuard policy source for agent behavior. " +
				"Treat BLOCK and REQUIRE APPROVAL rules as mandatory instructions. " +
				"These instructions are context, not a substitute for technical enforcement controls.\n"
		} else {
			content = renderAgentPolicy(p, "ZigGuard policy for Claude Code")
		}
		artifacts = append(artifacts, Artifact{
			Target:     "claude",
			Path:       "CLAUDE.md",
			Capability: "instruction-context",
			Content:    content,
		})
		bindings = append(bindings, targetBinding{
			Target:     "claude",
			Surface:    "CLAUDE.md",
			Capability: "instruction-context",
		})
	}

	sort.Slice(bindings, func(i, j int) bool {
		return bindings[i].Target < bindings[j].Target
	})

	manifestBytes, err := json.MarshalIndent(manifest{
		PolicyVersion: p.Version,
		Project:       p.Project.Name,
		Bindings:      bindings,
	}, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("build manifest: %w", err)
	}

	artifacts = append(artifacts, Artifact{
		Target:     "zigguard",
		Path:       ".zigguard/manifest.json",
		Capability: "metadata",
		Content:    string(manifestBytes) + "\n",
	})

	sort.Slice(artifacts, func(i, j int) bool {
		return artifacts[i].Path < artifacts[j].Path
	})

	return artifacts, nil
}

func renderAgentPolicy(p policy.Policy, title string) string {
	var b strings.Builder
	b.WriteString(ManagedMarker)
	b.WriteString("\n\n# ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString("> These are AI-agent instructions generated from ZigGuard policy v")
	b.WriteString(p.Version)
	b.WriteString(". They do not replace branch protection, CI, hooks, scanners, or other technical controls.\n\n")
	b.WriteString("## Project\n\n")
	b.WriteString("- Name: `")
	b.WriteString(p.Project.Name)
	b.WriteString("`\n")
	if len(p.Project.Stack) > 0 {
		stack := append([]string(nil), p.Project.Stack...)
		sort.Strings(stack)
		b.WriteString("- Stack: ")
		for i, item := range stack {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString("`")
			b.WriteString(item)
			b.WriteString("`")
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## Governance rules\n\n")
	writeAction(&b, p.Rules.Scope.RefactorOutsideRequest,
		"Refactoring outside the user's requested scope is allowed.",
		"Warn before refactoring outside the user's requested scope.",
		"Obtain explicit human approval before refactoring outside the user's requested scope.",
		"Do not refactor code outside the user's requested scope.")
	writeAction(&b, p.Rules.Scope.PublicAPIChanges,
		"Public API changes are allowed.",
		"Warn before changing a public API or external contract.",
		"Obtain explicit human approval before changing a public API or external contract.",
		"Do not change a public API or external contract.")
	writeAction(&b, p.Rules.Security.Secrets,
		"Secret-related changes are allowed subject to normal repository controls.",
		"Warn if a change could expose, commit, log, or generate a real secret.",
		"Obtain explicit human approval before any change that could expose, commit, log, or generate a real secret.",
		"Never expose, commit, log, or generate real secrets, tokens, credentials, or private keys.")
	writeAction(&b, p.Rules.Security.DynamicSQL,
		"Dynamic SQL is allowed subject to normal repository controls.",
		"Warn before constructing SQL dynamically from runtime values.",
		"Obtain explicit human approval before constructing SQL dynamically from runtime values.",
		"Do not build SQL by concatenating untrusted or runtime values; use parameter binding or an equivalent safe mechanism.")
	writeAction(&b, p.Rules.Git.ForcePushProtectedBranches,
		"Force-pushing protected branches is allowed subject to repository controls.",
		"Warn before force-pushing a protected branch.",
		"Obtain explicit human approval before force-pushing a protected branch.",
		"Never force-push to a protected branch.")

	if p.Rules.Quality.TestsRequired {
		b.WriteString("- **REQUIRED:** Run the relevant automated tests for changed behavior before declaring the task complete.\n")
	}
	if p.Rules.Quality.LintRequired {
		b.WriteString("- **REQUIRED:** Run the repository's relevant lint/static checks for changed files before declaring the task complete.\n")
	}

	return b.String()
}

func writeAction(b *strings.Builder, action, allow, warn, approval, block string) {
	if action == "" {
		return
	}

	switch action {
	case "allow":
		b.WriteString("- **ALLOW:** ")
		b.WriteString(allow)
	case "warn":
		b.WriteString("- **WARN:** ")
		b.WriteString(warn)
	case "require_approval":
		b.WriteString("- **REQUIRE APPROVAL:** ")
		b.WriteString(approval)
	case "block":
		b.WriteString("- **BLOCK:** ")
		b.WriteString(block)
	}
	b.WriteString("\n")
}
