package managed

import (
	"bytes"
	"errors"
	"fmt"
)

const (
	StartMarker  = "<!-- zigguard:managed:start -->"
	EndMarker    = "<!-- zigguard:managed:end -->"
	LegacyMarker = "<!-- Generated by ZigGuard. DO NOT EDIT. -->"
)

var ErrMalformed = errors.New("malformed ZigGuard managed section")

type State int

const (
	Missing State = iota
	Present
)

type Location struct {
	Start int
	End   int
}

func Wrap(body string) string {
	body = string(bytes.TrimRight([]byte(body), "\r\n"))
	return StartMarker + "\n" + body + "\n" + EndMarker + "\n"
}

func Locate(content []byte) (Location, State, error) {
	startMarker := []byte(StartMarker)
	endMarker := []byte(EndMarker)
	startCount := bytes.Count(content, startMarker)
	endCount := bytes.Count(content, endMarker)

	if startCount == 0 && endCount == 0 {
		return Location{}, Missing, nil
	}
	if startCount != 1 || endCount != 1 {
		return Location{}, Missing, fmt.Errorf("%w: expected exactly one start and one end marker", ErrMalformed)
	}

	start := bytes.Index(content, startMarker)
	endStart := bytes.Index(content, endMarker)
	if endStart < start {
		return Location{}, Missing, fmt.Errorf("%w: end marker appears before start marker", ErrMalformed)
	}

	end := endStart + len(endMarker)
	if end < len(content) {
		if content[end] == '\r' && end+1 < len(content) && content[end+1] == '\n' {
			end += 2
		} else if content[end] == '\n' {
			end++
		}
	}

	return Location{Start: start, End: end}, Present, nil
}

func Extract(content []byte) ([]byte, State, error) {
	location, state, err := Locate(content)
	if err != nil || state == Missing {
		return nil, state, err
	}
	section := make([]byte, location.End-location.Start)
	copy(section, content[location.Start:location.End])
	return section, Present, nil
}

func Merge(current, desired []byte) ([]byte, error) {
	if _, state, err := Locate(desired); err != nil || state != Present {
		if err != nil {
			return nil, fmt.Errorf("invalid desired managed section: %w", err)
		}
		return nil, errors.New("invalid desired managed section: markers are missing")
	}

	location, state, err := Locate(current)
	if err != nil {
		return nil, err
	}

	if state == Present {
		result := make([]byte, 0, len(current)-location.End+location.Start+len(desired))
		result = append(result, current[:location.Start]...)
		result = append(result, desired...)
		result = append(result, current[location.End:]...)
		return result, nil
	}

	legacy := []byte(LegacyMarker)
	if bytes.HasPrefix(current, legacy) {
		result := make([]byte, len(desired))
		copy(result, desired)
		return result, nil
	}
	if bytes.Contains(current, legacy) {
		return nil, fmt.Errorf("%w: legacy ZigGuard marker found outside the beginning of the file", ErrMalformed)
	}

	if len(current) == 0 {
		result := make([]byte, len(desired))
		copy(result, desired)
		return result, nil
	}

	result := append([]byte(nil), current...)
	if !bytes.HasSuffix(result, []byte("\n")) {
		result = append(result, '\n')
	}
	if !bytes.HasSuffix(result, []byte("\n\n")) {
		result = append(result, '\n')
	}
	result = append(result, desired...)
	return result, nil
}
